### PR TITLE
CDAP-7210 Check for usage of deprecated items; fix documentation build

### PR DESCRIPTION
**Pull request by awholegunch**
Adds a Python tool to detect usage of deprecated items in documentation and examples.

Fixes changes introduced by https://github.com/caskdata/cdap-apps/pull/126 into the WISE.
(which breaks the doc build: see https://builds.cask.co/browse/CDAP-DQB-17)

Running as a Quick Build: http://builds.cask.co/browse/CDAP-DQB164-1

### CODE REVIEW

File: cdap-docs/tools/docs-search-deprecated.py [hunk 1]
```diff
@@ -0,0 +1,142 @@
...
+
+try:
+    from bs4 import BeautifulSoup
+    from optparse import OptionParser
+    import os
+    import sys
+    import urllib2
+except Exception, e:
+    print "\nAre you running under Python 2.7? It's required.\n"
+    raise
```
Comment (anwar6953) [inline cdap-docs/tools/docs-search-deprecated.py]: this raises the original exception?

Comment (awholegunch) [reply cdap-docs/tools/docs-search-deprecated.py]: Yes. And gives an explanitory stack-trace, such as:

```
$ ./docs-search-deprecated.py

Are you running under Python 2.7? It's required.

Traceback (most recent call last):
  File "./docs-search-deprecated.py", line 29, in <module>
    from bs4 import BeautifulSoup
  File "/Users/john/.virtualenvs/py2.6/lib/python2.6/site-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/Users/john/.virtualenvs/py2.6/lib/python2.6/site-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/Users/john/.virtualenvs/py2.6/lib/python2.6/site-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
```

Comment (awholegunch) [reply cdap-docs/tools/docs-search-deprecated.py]: Looks like it depends on the version of 2.6 that is invoked; some cause an error message to be raised instead of the stack trace and exception. Fixed.

File: cdap-docs/tools/docs-search-deprecated.py [hunk 2]
```diff
@@ -25,15 +25,17 @@
...
-    import os
-    import sys
     import urllib2
 except Exception, e:
-    print "\nAre you running under Python 2.7? It's required.\n"
-    raise
+    if sys.version_info < (2, 7):
+        raise Exception("Must use python 2.7 or greater\n" + str(e))
+    else:
+        raise Exception(e)
```
Comment (anwar6953) [inline cdap-docs/tools/docs-search-deprecated.py]: I think you can just do `raise e`. Not sure what the difference would be.

Comment (awholegunch) [reply cdap-docs/tools/docs-search-deprecated.py]: Yes you can, as `e` is of `<type 'exceptions.AttributeError'>`. Amounts to about the same, as Python is very forgiving that way. But for simpliicty, we can use `raise e`.

Comment (awholegunch) [reply cdap-docs/tools/docs-search-deprecated.py]: Actually, the type of `e` will vary, but you get the idea. When I tested it, that was what it was throwing...

**Comment by anwar6953** [comment]
lgtm
