### PR TITLE
[CDAP-6359] Allow BatchContext to create datasets and check if datasets exist

### PR DESCRIPTION
**Pull request by knazir**
Part of Hydrator macros. Leveraged Admin's createDataset and datasetExists to allow Batch plugins to check for the existence of and create datasets in prepareRun.

### CODE REVIEW

**Comment by knazir** [comment]
Uh hold on really stupid checkstyle/compilation errors.

**Comment by knazir** [comment]
Ok after having a really bad time with checkstyle, it compiles. The unit test passed individually. Waiting on bamboo build to complete.

**Comment by knazir** [comment]
Completed build: http://builds.cask.co/browse/CDAP-DUT4327-3

**Comment by knazir** [comment]
Need to fix some nasty stuff I just did with rebasing..
